<?php
function elasticsearch_menu() {
    $items = array();

    $items['elasticsearch/search'] = array(
        'title' => 'Search COEP Website',
        'page callback' => 'perform_search',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
     );

    return $items;
}

function search_it($query){
	$ch = curl_init();
	$host = 'localhost:9200';
	if($socket =@ fsockopen($host, 9200, $errno, $errstr, 30)) { #checking if the search engine is working and online
		fclose($socket);
		$url = "http://localhost:9200/url-test/_search?pretty";
		$param = "{\"query\" : {\"query_string\" : { \"query\" : \"$query\"}}}";
		curl_setopt($ch, CURLOPT_URL ,$url);
		curl_setopt($ch, CURLOPT_HEADER, 0);
		curl_setopt($ch, CURLOPT_POSTFIELDS, $param);
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
		$result = curl_exec($ch);
		curl_close($ch);
		return $result;
	}
	else {
		return "Search engine seems offline";
	}
}

function perform_search() {
    $vars = array();
    $vars['type']="div";
    $vars['title'] = "";
    $vars['attributes']=array("");
    $vars['items'][0]="<form action = \"http://localhost/drupal/elasticsearch/search\"><input name = \"query\" type = \"Text\" placeholder=\"Enter the query\"> </input><br/><input type = \"submit\"></input></form> <div id = \"search_results\"></div>";
    //Ajinkya, please improve the UI here.
    //Try returning a random JSON object from search_it function and try to display its content as any good search results should look.
    //This is just a baseline I have created.

    if(array_key_exists('query', $_GET)){
    	$data = search_it($_GET['query']);
    	$vars['items'][1] = "<script type = 'text/javascript'>
    						var JSDATA = ". json_encode($data, JSON_HEX_TAG | JSON_HEX_AMP ) . ";
    						newVar = JSON.parse(JSDATA);
    						var len = newVar['hits']['hits'].length;
    						var count = 0;
    						var result_data = '';
    						for(count = 0; count < len; count++){
    							result_data += '<a target=\"_blank\" href = \"' + newVar['hits']['hits'][count]['_source']['link'] + '\" ><h2>' + newVar['hits']['hits'][count]['_source']['title'] + '</h2></a>'
    							result_data += '<h3>' + newVar['hits']['hits'][count]['_source']['content'] + '</h3> <br/>'
    						}
				            document.getElementById('search_results').innerHTML = result_data;
				    		</script>";
				    		//due to the JSON structure returned by elasticsearch, the access to e
    }
    //create a search UI
    //input a search query and if input query is available, call 'search_it(query) function and results are then displayed'

    return theme_item_list($vars);
}